"""empty message

Revision ID: 171d32aa0e71
Revises: 289c7a070f91
Create Date: 2017-12-10 14:52:13.403119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d32aa0e71'
down_revision = '289c7a070f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drips', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.add_column('stages', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.add_column('stages', sa.Column('variables', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'variables')
    op.drop_column('stages', 'is_sent')
    op.drop_column('drips', 'is_enabled')
    # ### end Alembic commands ###
