"""empty message

Revision ID: 7a4f128284e8
Revises: 942a3e847318
Create Date: 2017-12-13 01:14:41.459686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4f128284e8'
down_revision = '942a3e847318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('credential', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_users')
    # ### end Alembic commands ###
