"""empty message

Revision ID: 942a3e847318
Revises: 171d32aa0e71
Create Date: 2017-12-11 15:26:26.523985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942a3e847318'
down_revision = '171d32aa0e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drips', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drips', 'is_completed')
    # ### end Alembic commands ###
