"""empty message

Revision ID: bef69a4676d2
Revises: ef1368f9347f
Create Date: 2017-12-14 00:48:19.288990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef69a4676d2'
down_revision = 'ef1368f9347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_users')
    op.add_column('users', sa.Column('message_thread', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'message_thread')
    op.create_table('google_users',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('credential', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'google_users_pkey')
    )
    # ### end Alembic commands ###
